kind: Deployment
apiVersion: apps/v1
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
    app.kubernetes.io/component: reverse-proxy
    app.kubernetes.io/instance: reverse-proxy
  
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: reverse-proxy
  template:
    metadata:
      labels:
        deployment: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: >-
            image-registry.openshift-image-registry.svc:5000/node11app/nginxbase@sha256:e97be88e043b3d3e6f74228c64206f09c67a74d92c82509a749704875379961b
          ports:
            - hostPort: 8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: NODEIP
              value: 10.10.10.20
            - name: SVCNAME
              value: springboot-openshift-git2
            - name: SVCPORT
              value: '8080'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        edage: test
      hostNetwork: true
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  paused: false
